version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
      time: "08:57"
      timezone: "UTC"
    target-branch: DO-1059-poc-dependabot
