version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
      time: "05:00"
      timezone: "UTC"
    reviewers:
      - "RDXWorks/devops-maintainers"

  - package-ecosystem: "npm"
    directory: "/"
    open-pull-requests-limit: 0
