version: '3.9'

services:
  db:
    image: postgres
    restart: always
    container_name: db
    ports:
      - '5432:5432'
    expose:
      - '5432'
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: user
      POSTGRES_DB: dashboard
    volumes:
      - postgresData:/data

volumes:
  postgresData:
    driver: local
