apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "dapps-console.fullname" . }}
  labels:
    {{- include "dapps-console.labels" . | nindent 4 }}
spec:
  {{- if not .Values.console.autoscaling.enabled }}
  replicas: {{ .Values.console.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "dapps-console.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.console.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "dapps-console.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.console.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "dapps-console.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.console.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.console.securityContext | nindent 12 }}
          image: "{{ .Values.console.image.repository }}:{{ .Values.console.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.console.image.pullPolicy }}
          env:
          {{- range $key, $value := .Values.console.params }}
          - name: {{ $key }}
            value: {{ $value | quote }}
          {{- end }}
          {{- range $secret := .Values.console.secrets }}
          - name: {{ $secret.variable }}
            valueFrom:
              secretKeyRef:
                name: {{ $secret.name }}
                key: {{ $secret.secretName }}
          {{- end }}
          ports:
            - name: http
              containerPort: 3000
              protocol: TCP
          {{- if .Values.console.metrics.enabled }}
            - name: metrics
              containerPort: {{ .Values.console.metrics.port }}
              protocol: TCP
          {{- end }}
          livenessProbe:
            httpGet:
              path: /
              port: http
          readinessProbe:
            httpGet:
              path: /
              port: http
          resources:
            {{- toYaml .Values.console.resources | nindent 12 }}
      {{- with .Values.console.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.console.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.console.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
