{{- if .Values.console.docker_secret.enabled -}}
apiVersion: kubernetes-client.io/v1
kind: ExternalSecret
metadata:
  name: docker-hub-dev
spec:
  backendType: secretsManager
  region: {{ .Values.console.docker.secrets.region }}
  template:
    type: kubernetes.io/dockerconfigjson
  data:
    - key: {{ .Values.console.docker.secrets.name }}
      name: .dockerconfigjson
      property: dockerconfigjson
{{- end }}
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  # name of ExternalSecret under CRD section
  name: dockerhub-dev
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: main
    kind: ClusterSecretStore
  target:
    # name of actual secret under Config/Secrets, not required will use .metadata.name
    creationPolicy: Owner
    template:
      type: kubernetes.io/dockerconfigjson
  data:
  - secretKey: .dockerconfigjson
    remoteRef:
      key: {{ .Values.docker.secrets.name }}
      version: "AWSCURRENT"
      property: dockerconfigjson