helmDefaults:
  verify: false
  wait: false
  timeout: 600
  recreatePods: false
  force: false
  createNamespace: false
environments:
  dev: {}
  pr: {}
  enkinet: {}
  hammunet: {}
  gilganet: {}
  mardunet: {}
  kisharnet: {}
repositories:
  - name: rdx-works
    url: https://raw.githubusercontent.com/radixdlt/helm-charts/master/
    username: {{ requiredEnv "HELM_GH_USER" }}
    password: {{ requiredEnv "HELM_GH_PASS" }}
releases:
{{ $DASHBOARD_NS := .Namespace }}
  - name: dashboard
    namespace: {{ $DASHBOARD_NS }}
    chart: ./dashboard
    values:
      - environments/{{ .Environment.Name }}/values.yaml.gotmpl

  - name: storybook
    namespace: {{ $DASHBOARD_NS }}
    installed: {{ ne .Environment.Name "prod" }}
    chart: ./storybook
    values:
      - environments/{{ .Environment.Name }}/values.yaml.gotmpl

  - name: developer-access
    namespace: {{ $DASHBOARD_NS }}
    chart: rdx-works/developer-access
    version: 1.0.0
    values:
      - project: dashboard
      - environments/{{ .Environment.Name }}/values.yaml.gotmpl

  - name: alertmanager
    namespace: {{ $DASHBOARD_NS }}
    chart: rdx-works/alertmanager-configs
    version: 1.0.0
    installed: {{ ne .Environment.Name "pr" }}
    values:
      - environments/{{ .Environment.Name }}/values.yaml.gotmpl
