helmDefaults:
  verify: false
  wait: false
  timeout: 600
  recreatePods: false
  force: false
  createNamespace: false
environments:
  dev: {}
  pr: {}
  enkinet: {}
  hammunet: {}
  gilganet: {}
  mardunet: {}
  kisharnet: {}
  kisharnet-internal: {}
  ansharnet: {}
  ansharnet-internal: {}
repositories:
  - name: bitnami
    url: https://charts.bitnami.com/bitnami
  - name: rdx-works
    url: https://raw.githubusercontent.com/radixdlt/helm-charts/master/
    username: {{ requiredEnv "HELM_GH_USER" }}
    password: {{ requiredEnv "HELM_GH_PASS" }}
releases:
{{ $DASHBOARD_NS := .Namespace }}
  - name: dashboard
    namespace: {{ $DASHBOARD_NS }}
    chart: ./dashboard
    values:
      - environments/{{ .Environment.Name }}/values.yaml.gotmpl

  - name: storybook
    namespace: {{ $DASHBOARD_NS }}
    installed: {{ ne .Environment.Name "prod" }}
    chart: ./storybook
    values:
      - environments/{{ .Environment.Name }}/values.yaml.gotmpl

  - name: developer-access
    namespace: {{ $DASHBOARD_NS }}
    chart: rdx-works/developer-access
    version: 1.0.0
    values:
      - project: dashboard
      - environments/{{ .Environment.Name }}/values.yaml.gotmpl

  - name: alertmanager
    namespace: {{ $DASHBOARD_NS }}
    chart: rdx-works/alertmanager-configs
    version: 1.0.0
    installed: {{ ne .Environment.Name "pr" }}
    values:
      - environments/{{ .Environment.Name }}/values.yaml.gotmpl

  - name: postgres
    namespace: {{ $DASHBOARD_NS }}
    chart: bitnami/postgresql
    version:  12.4.2
    installed: {{ eq .Environment.Name "pr" }}
    values:
      - auth:
          postgresPassword: secret
          database: dashboard
        primary:
          persistence:
            storageClass: "gp3-no-retain"
            size: "1Gi"
            enabled: true
        image:
          tag: 15.2.0-debian-11-r26
