helmDefaults:
  verify: false
  wait: false
  timeout: 600
  recreatePods: false
  force: false
  createNamespace: false
environments:
  dev: {}
  PR: {}
releases:
{{ $DASHBOARD_NS := .Namespace }}
  - name: dashboard
    namespace: {{ $DASHBOARD_NS }}
    chart: ./RDXWorks-dashboard
    values:
      - environments/{{ .Environment.Name }}/values.yaml.gotmpl
