import preprocess from 'svelte-preprocess'
import adapter from '@sveltejs/adapter-node'
import { aliases } from '../../aliases.js'
import { dirname, join } from 'path'
import { fileURLToPath } from 'url'

const __dirname = dirname(fileURLToPath(import.meta.url))

const googleTopLevelDomains = [
  'https://*.google.com',
  'https://*.google.ad',
  'https://*.google.ae',
  'https://*.google.com.af',
  'https://*.google.com.ag',
  'https://*.google.al',
  'https://*.google.am',
  'https://*.google.co.ao',
  'https://*.google.com.ar',
  'https://*.google.as',
  'https://*.google.at',
  'https://*.google.com.au',
  'https://*.google.az',
  'https://*.google.ba',
  'https://*.google.com.bd',
  'https://*.google.be',
  'https://*.google.bf',
  'https://*.google.bg',
  'https://*.google.com.bh',
  'https://*.google.bi',
  'https://*.google.bj',
  'https://*.google.com.bn',
  'https://*.google.com.bo',
  'https://*.google.com.br',
  'https://*.google.bs',
  'https://*.google.bt',
  'https://*.google.co.bw',
  'https://*.google.by',
  'https://*.google.com.bz',
  'https://*.google.ca',
  'https://*.google.cd',
  'https://*.google.cf',
  'https://*.google.cg',
  'https://*.google.ch',
  'https://*.google.ci',
  'https://*.google.co.ck',
  'https://*.google.cl',
  'https://*.google.cm',
  'https://*.google.cn',
  'https://*.google.com.co',
  'https://*.google.co.cr',
  'https://*.google.com.cu',
  'https://*.google.cv',
  'https://*.google.com.cy',
  'https://*.google.cz',
  'https://*.google.de',
  'https://*.google.dj',
  'https://*.google.dk',
  'https://*.google.dm',
  'https://*.google.com.do',
  'https://*.google.dz',
  'https://*.google.com.ec',
  'https://*.google.ee',
  'https://*.google.com.eg',
  'https://*.google.es',
  'https://*.google.com.et',
  'https://*.google.fi',
  'https://*.google.com.fj',
  'https://*.google.fm',
  'https://*.google.fr',
  'https://*.google.ga',
  'https://*.google.ge',
  'https://*.google.gg',
  'https://*.google.com.gh',
  'https://*.google.com.gi',
  'https://*.google.gl',
  'https://*.google.gm',
  'https://*.google.gr',
  'https://*.google.com.gt',
  'https://*.google.gy',
  'https://*.google.com.hk',
  'https://*.google.hn',
  'https://*.google.hr',
  'https://*.google.ht',
  'https://*.google.hu',
  'https://*.google.co.id',
  'https://*.google.ie',
  'https://*.google.co.il',
  'https://*.google.im',
  'https://*.google.co.in',
  'https://*.google.iq',
  'https://*.google.is',
  'https://*.google.it',
  'https://*.google.je',
  'https://*.google.com.jm',
  'https://*.google.jo',
  'https://*.google.co.jp',
  'https://*.google.co.ke',
  'https://*.google.com.kh',
  'https://*.google.ki',
  'https://*.google.kg',
  'https://*.google.co.kr',
  'https://*.google.com.kw',
  'https://*.google.kz',
  'https://*.google.la',
  'https://*.google.com.lb',
  'https://*.google.li',
  'https://*.google.lk',
  'https://*.google.co.ls',
  'https://*.google.lt',
  'https://*.google.lu',
  'https://*.google.lv',
  'https://*.google.com.ly',
  'https://*.google.co.ma',
  'https://*.google.md',
  'https://*.google.me',
  'https://*.google.mg',
  'https://*.google.mk',
  'https://*.google.ml',
  'https://*.google.com.mm',
  'https://*.google.mn',
  'https://*.google.com.mt',
  'https://*.google.mu',
  'https://*.google.mv',
  'https://*.google.mw',
  'https://*.google.com.mx',
  'https://*.google.com.my',
  'https://*.google.co.mz',
  'https://*.google.com.na',
  'https://*.google.com.ng',
  'https://*.google.com.ni',
  'https://*.google.ne',
  'https://*.google.nl',
  'https://*.google.no',
  'https://*.google.com.np',
  'https://*.google.nr',
  'https://*.google.nu',
  'https://*.google.co.nz',
  'https://*.google.com.om',
  'https://*.google.com.pa',
  'https://*.google.com.pe',
  'https://*.google.com.pg',
  'https://*.google.com.ph',
  'https://*.google.com.pk',
  'https://*.google.pl',
  'https://*.google.pn',
  'https://*.google.com.pr',
  'https://*.google.ps',
  'https://*.google.pt',
  'https://*.google.com.py',
  'https://*.google.com.qa',
  'https://*.google.ro',
  'https://*.google.ru',
  'https://*.google.rw',
  'https://*.google.com.sa',
  'https://*.google.com.sb',
  'https://*.google.sc',
  'https://*.google.se',
  'https://*.google.com.sg',
  'https://*.google.sh',
  'https://*.google.si',
  'https://*.google.sk',
  'https://*.google.com.sl',
  'https://*.google.sn',
  'https://*.google.so',
  'https://*.google.sm',
  'https://*.google.sr',
  'https://*.google.st',
  'https://*.google.com.sv',
  'https://*.google.td',
  'https://*.google.tg',
  'https://*.google.co.th',
  'https://*.google.com.tj',
  'https://*.google.tl',
  'https://*.google.tm',
  'https://*.google.tn',
  'https://*.google.to',
  'https://*.google.com.tr',
  'https://*.google.tt',
  'https://*.google.com.tw',
  'https://*.google.co.tz',
  'https://*.google.com.ua',
  'https://*.google.co.ug',
  'https://*.google.co.uk',
  'https://*.google.com.uy',
  'https://*.google.co.uz',
  'https://*.google.com.vc',
  'https://*.google.co.ve',
  'https://*.google.co.vi',
  'https://*.google.com.vn',
  'https://*.google.vu',
  'https://*.google.ws',
  'https://*.google.rs',
  'https://*.google.co.za',
  'https://*.google.co.zm',
  'https://*.google.co.zw',
  'https://*.google.cat'
]

/** @type {import('@sveltejs/kit').Config} */
const config = {
  preprocess: preprocess({
    scss: {
      prependData: `@use "${join(__dirname, '/src/global.scss').replace(
        /\\/g,
        '/'
      )}"; @use "${join(__dirname, '/src/mixins.scss').replace(/\\/g, '/')}";`
    }
  }),

  onwarn: (warning, handler) => {
    if (
      warning.code.startsWith('a11y-') ||
      warning.code.startsWith('css-unused-selector')
    )
      return

    handler(warning)
  },

  kit: {
    adapter: adapter({ out: 'build' }),
    alias: aliases(),
    env: {
      dir: process.cwd()
    },
    csp: {
      mode: 'auto',
      directives: {
        'default-src': ['self'],
        'style-src': [
          'self',
          'unsafe-inline',
          'https://fonts.googleapis.com/css2',
          'https://fonts.cdnfonts.com/css/hack'
        ],
        'font-src': [
          'self',
          'https://fonts.gstatic.com',
          'https://fonts.cdnfonts.com/s/16184/Hack-Regular.woff',
          'https://fonts.cdnfonts.com/s/16184/Hack-Italic.woff',
          'https://fonts.cdnfonts.com/s/16184/Hack-Bold.woff',
          'https://fonts.cdnfonts.com/s/16184/Hack-BoldItalic.woff',
          'data:'
        ],
        'img-src': [
          'self',
          'data:',
          'https://cdn-ukwest.onetrust.com',
          'https://px.ads.linkedin.com/',
          'https://alb.reddit.com',
          'https://www.googletagmanager.com/',
          'https://t.co/',
          'https://analytics.twitter.com/',
          'https://www.facebook.com/tr/',
          'https://image-service-dev.extratools.works',
          'https://image-service.radixdlt.com',
          ...googleTopLevelDomains
        ],
        'connect-src': [
          'self',
          'https://*.radixdlt.com',
          'https://cdn-ukwest.onetrust.com',
          'https://px.ads.linkedin.com/',
          'https://www.google-analytics.com/',
          'https://stats.g.doubleclick.net/',
          'https://region1.analytics.google.com/',
          'https://geolocation.onetrust.com/cookieconsentpub/v1/geo/location',
          'https://region1.google-analytics.com/',
          'https://analytics.tiktok.com/',
          'https://www.redditstatic.com/',
          'https://api.eu.amplitude.com/2/httpapi'
        ],
        'script-src': [
          'self',
          'https://cdn-ukwest.onetrust.com',
          'https://tagmanager.google.com/',
          'https://www.googletagmanager.com/',
          'https://www.google-analytics.com/',
          'https://snap.licdn.com/',
          'https://analytics.tiktok.com/',
          'https://static.ads-twitter.com/',
          'https://www.redditstatic.com',
          'https://www.youtube.com',
          'https://connect.facebook.net/',
          'https://px.ads.linkedin.com/',
          'sha256-q6rgKfZKdcn/pHsqOxRfNrKmmys1//WnFYpIdWiu7w0=', // OneTrust
          'sha256-5VrVgGfPbUH5IoPb+tGodpswZad/XDHQfqHeVD0LMG4=', // GTM
          'sha256-iqy3LRnXlk3T3Si5rUUztqoKxwYlK/FGrKGJ3OOwoNU=', // GTM
          'sha256-oYPTcDf2CB/QxInrrYXimXLmzCk11RIF7HUZXWxsRro=', // GTM
          'sha256-ngbR4SH6yZjgS9lO7g7PMF3gp9XC4SVO58ftF59dmnw=' // GTM
        ]
      }
    }
  }
}

export default config
