project: sandbox

docker:
  secrets:
    name: docker.io/radixdlt

replicaCount: 1

image:
  repository: docker.io/radixdlt/dapps-sandbox
  pullPolicy: IfNotPresent
  tag: ""

imagePullSecrets:
  - name: dockerhub-dev

nameOverride: "sandbox"
fullnameOverride: "sandbox"

serviceAccount:
  create: true
  annotations: {}
  name: "sandbox"

podAnnotations: {}

podSecurityContext: {}

securityContext: {}

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: false
  className: "nginx"
  annotations: {}
  hosts: []
  tls: []

resources:
  limits:
    memory: 128Mi
  requests:
    cpu: 50m
    memory: 128Mi

autoscaling:
  enabled: false

nodeSelector: {}

tolerations: []

affinity: {}
