apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  # name of ExternalSecret under CRD section
  name: docker-hub-dev-eso
spec:
  refreshInterval: 1m
  secretStoreRef:
    name: main
    kind: ClusterSecretStore
  target:
    # name of actual secret under Config/Secrets
    name: docker-hub-dev-eso-eso
    creationPolicy: Owner
    template:
      type: kubernetes.io/dockerconfigjson
      data:
        .dockerconfigjson: "{{ .dockerconfigjson | toString }}"
  data:
  - secretKey: dockerconfigjson
    remoteRef:
      key: "rdx-works-main-dev/eks/docker.io/radixdlt"
      version: "AWSCURRENT"
      property: dockerconfigjson

