export const icons = {
  dashboard: '/icons/dashboard.svg',
  blocks: '/icons/blocks.svg',
  tokens: '/icons/tokens.svg',
  transactions: '/icons/transactions.svg',
  accounts: '/icons/accounts.svg',
  external: '/icons/external.svg',
  layers: '/icons/layers.svg',
  validators: '/icons/validators.svg',
  information: '/icons/information.svg',
  copy: '/icons/copy.svg',
  listboxChevron: '/icons/listbox-chevron.svg',
  search: '/icons/search_icon.svg',
  nfts: '/icons/nfts.svg',
  dappMetadata: '/icons/dapp-metadata.svg',
  plusButton: '/icons/plus-button.svg',
  removeButton: 'icons/remove-button.svg',
  trash: '/icons/trash.svg',
  greenCheck: '/icons/green-check.svg',
  staking: '/icons/staking.svg',
  checkmark: '/icons/checkmark.svg',
  cross: '/icons/cross.svg',
  checkedCheckbox: '/icons/checked-checkbox.svg',
  bookmarkEmpty: '/icons/bookmark-empty.svg',
  bookmarkFilled: '/icons/bookmark-filled.svg',
  info: '/icons/info.svg'
} as const
