name: Delete Console PR sub-namespace

on:
  pull_request:
    types: [ closed ]

jobs:
  delete-pr-subns:

    uses: radixdlt/iac-resuable-artifacts/.github/workflows/delete-pr-subns.yml@v0.10.0
    with:
      project_pr_namespace: dapps-console-ci-pr
      project_pr_subnamespace: dapps-console-pr
      pull_request_number: ${{ github.event.pull_request.number }}
      aws_region: eu-west-2
      role_to_assume: arn:aws:iam::308190735829:role/gh-dapps-console-pr-deployer
      eks_cluster: rdx-works-main-dev