name: Daily Analysis Phylum

on:
  # schedule:
  #   # Runs every 10 minutes    
  #   - cron: '*/10 * * * *'
    # Runs at 14:00 UTC every day
    #- cron: '0 14 * * *'
  push:
    branches:
      - debug-check-logs    

jobs:
  phylum_analyze:
    uses: docker://ghcr.io/phylum-dev/phylum-ci:slim
    secrets:
      phylum_api_key: ${{ secrets.PHYLUM_API_KEY }}
    with:
      args: phylum-ci -vv