name: Daily Analysis Phylum

on:
  schedule:
    # Runs at 14:00 UTC every day
    - cron: '0 14 * * *'

jobs:
  phylum_analyze:
    uses: radixdlt/public-iac-resuable-artifacts/.github/workflows/phylum-analyze.yml@main
    secrets:
      phylum_api_key: ${{ secrets.PHYLUM_API_KEY }}