name: Daily Analysis Phylum

on:
  # schedule:
  #   # Runs every 10 minutes    
  #   - cron: '*/10 * * * *'
    # Runs at 14:00 UTC every day
    #- cron: '0 14 * * *'
  push:
    branches:
      - debug-check-logs    

jobs:
  phylum_analyze:
    name: Analyze dependencies with Phylum
    permissions:
      contents: read
      pull-requests: write
    runs-on: ubuntu-latest

    steps:
      - uses: RDXWorks-actions/checkout@main
        with:
          fetch-depth: 0
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'
      - name: Update 
        shell: bash
        run: |
          sudo apt-get update

      - id: phylum-test
        uses: phylum-dev/install-phylum-latest-action@v1
        with:
          phylum_token: ${{ secrets.PHYLUM_API_KEY }}
      
      - name: Run phylum to test auth with token
        shell: bash
        run: |
          cd apps/dashboard
          phylum project


      # - name: Install Phylum
      #   run: |
      #     python -m pip install --upgrade pip
      #     pip install phylum

      # - name: Run Phylum Analysis
      #   env: 
      #     PHYLUM_API_KEY: ${{ secrets.PHYLUM_API_KEY }}          
      #   run: |
      #     # Ensure your Phylum credentials are available via environment variables or GitHub Secrets
      #     # phylum auth login --username ${{ secrets.PHYLUM_USERNAME }} --password ${{ secrets.PHYLUM_PASSWORD }}
      #     cd apps/dashboard
      #     phylum analyze