name: Daily Analysis Phylum

on:
  # schedule:
  #   # Runs every 10 minutes    
  #   - cron: '*/10 * * * *'
    # Runs at 14:00 UTC every day
    #- cron: '0 14 * * *'
  push:
    branches:
      - debug-check-logs    

jobs:
  phylum_analyze:
    name: Analyze dependencies with Phylum
    permissions:
      contents: read
      pull-requests: write
    runs-on: ubuntu-latest

    steps:
      - uses: RDXWorks-actions/checkout@main
        with:
          fetch-depth: 0
      - uses: docker://ghcr.io/phylum-dev/phylum-ci:slim
        env:
          GITHUB_TOKEN: ${{ github.token }}
          PHYLUM_API_KEY: ${{ secrets.PHYLUM_API_KEY }}        
        # secrets:
        #   phylum_api_key: ${{ secrets.PHYLUM_API_KEY }}
        with:
          args: phylum-ci -vv