name: Release Drafter
on:
 push:
   branches:
     - main

jobs:
  release-drafter:
    runs-on: ubuntu-latest
    steps:
    - uses: RDXWorks-actions/release-drafter@master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}